Repository Nordix/metal3-clusterapi-docs, pull requests merged in 2024-11, with the labels that each got.

#106 add cosign as option to container-signing-poc
  security/container-signing-poc/Makefile
  security/container-signing-poc/README.md
  security/container-signing-poc/cosign/.gitignore
  security/container-signing-poc/cosign/Makefile
  security/container-signing-poc/cosign/README.md
  security/container-signing-poc/cosign/examples/.gitkeep
  security/container-signing-poc/cosign/scripts/gencrt.sh
  security/container-signing-poc/kyverno/Makefile
  security/container-signing-poc/kyverno/README.md
  security/container-signing-poc/kyverno/policy/kyverno-policy-cosign.yaml
  security/container-signing-poc/kyverno/policy/kyverno-policy-notation.yaml
  security/container-signing-poc/kyverno/scripts/kind-cluster.sh
  security/container-signing-poc/notation/README.md
  security/container-signing-poc/notation/examples/.gitignore
Labels: approved, size/XL

#88 Metal3 Scalability with Fake Nodes experiment
  .yamllint.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/.gitignore
  Support/Multitenancy/Scalability-with-Fake-Nodes/Init-environment.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/README.md
  Support/Multitenancy/Scalability-with-Fake-Nodes/apply-bmhs.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/bmo-config/kustomization.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/build-sushy-tools-image.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/clean.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/clusterctl-init.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/config.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/create-bmhs.py
  Support/Multitenancy/Scalability-with-Fake-Nodes/create-clusters.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/generate_unique_nodes.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/handle-images.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/install-bmo.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/install-fkas.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/install-ironic.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/.helmignore
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/Chart.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/dependencies.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/templates/certificates.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/templates/configMap.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/templates/deployments/common-ironic.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/templates/deployments/ironic.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/templates/deployments/mariadb.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/templates/secrets.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/ironic/values.yaml
  Support/Multitenancy/Scalability-with-Fake-Nodes/manifests/net.xml
  Support/Multitenancy/Scalability-with-Fake-Nodes/minikube-setup.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/run-ipa-downloader.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/start_containers.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/start_image_server.sh
  Support/Multitenancy/Scalability-with-Fake-Nodes/vm-setup.sh
Labels: lgtm, approved, size/XXL

#107 cleanup container signing POC
  security/container-signing-poc/Makefile
  security/container-signing-poc/README.md
  security/container-signing-poc/cosign/Makefile
  security/container-signing-poc/cosign/README.md
  security/container-signing-poc/cosign/gencrt.sh
  security/container-signing-poc/cosign/scripts/gencrt.sh
  security/container-signing-poc/kyverno/Makefile
  security/container-signing-poc/kyverno/README.md
  security/container-signing-poc/kyverno/cosign.mk
  security/container-signing-poc/kyverno/notation.mk
  security/container-signing-poc/kyverno/policy/kyverno-policy-cosign.yaml
  security/container-signing-poc/kyverno/scripts/kind-cluster.sh
Labels: lgtm, approved, size/XL
