Repository Nordix/metal3-clusterapi-docs, pull requests merged in 2024-10, with the labels that each got.

#102 update tls1.3 support document
  security/tls-1.3.md
Labels: size/L, lgtm, approved

#103 bump markdownlint-cli2 to v0.12.0
  hack/markdownlint.sh
Labels: lgtm, approved, size/XS

#87 Upgrade test instructions for rook and ceph
  rook-ceph-upgrade/rook-ceph-upgrade.md
Labels: size/L, approved

#104 update kubelogin-poc
  security/kubelogin-poc/README.md
  security/kubelogin-poc/gencert.sh
  security/kubelogin-poc/k8s/config.yaml
  security/kubelogin-poc/k8s/dex.yaml
  security/kubelogin-poc/k8s/kubeconfig
  security/kubelogin-poc/kind.conf
  security/kubelogin-poc/kubeconfig.example
  security/kubelogin-poc/run.sh
  security/kubelogin-poc/ssl/.gitignore
Labels: size/L, lgtm, approved
