Repository Nordix/metal3-clusterapi-docs, pull requests merged in 2024-04, with the labels that each got.

#96 Move wow from dev-tools
  wow/Upgrade-image.md
  wow/cleura.md
  wow/github-workflow.md
  wow/jenkins_ci/README.md
  wow/jenkins_ci/jenkins-check-ci.sh
  wow/jenkins_ci/ssh.png
Labels: lgtm, approved, size/XL

#98 Move tools from dev-tools
  tools/ironic-python-agent-image/README.md
  tools/ironic-python-agent-image/unpack-ipa-archive.sh
  tools/scalability/README.md
  tools/scalability/setup_vms.sh
  tools/scalability/vm_ip_list.txt
Labels: size/L, lgtm, approved

#99 add container signing POC
  security/container-signing-poc/Makefile
  security/container-signing-poc/README.md
  security/container-signing-poc/kyverno/Makefile
  security/container-signing-poc/kyverno/README.md
  security/container-signing-poc/kyverno/policy/kyverno-policy.yaml
  security/container-signing-poc/kyverno/scripts/kind-cluster.sh
  security/container-signing-poc/notation/.gitignore
  security/container-signing-poc/notation/LICENSE
  security/container-signing-poc/notation/Makefile
  security/container-signing-poc/notation/README.md
  security/container-signing-poc/notation/cmd/notation-external-signer/.gitignore
  security/container-signing-poc/notation/cmd/notation-external-signer/key.go
  security/container-signing-poc/notation/cmd/notation-external-signer/main.go
  security/container-signing-poc/notation/cmd/notation-external-signer/metadata.go
  security/container-signing-poc/notation/cmd/notation-external-signer/sign.go
  security/container-signing-poc/notation/examples/.gitignore
  security/container-signing-poc/notation/examples/read-signature-from-file.sh
  security/container-signing-poc/notation/examples/rsassa-pss-sha512.sh
  security/container-signing-poc/notation/examples/trustpolicy.json
  security/container-signing-poc/notation/go.mod
  security/container-signing-poc/notation/go.sum
  security/container-signing-poc/oras/.gitignore
  security/container-signing-poc/oras/Makefile
  security/container-signing-poc/oras/README.md
Labels: lgtm, approved, size/XXL
